### ISSUE TITLE
Unable to import ODST bsp with .ass script

### ISSUE THREAD

**Issue by GodHatesWeebs** [General-101/Halo-Asset-Blender-Development-Toolset#100]
Hi im trying to get the entire mombassa map in blender for an animation
all the BSPs in the tags>levels>atlas>h100 folder work fine except for h100_030 and h100_080
i get this error

Python: Traceback (most recent call last):
  File "C:\Users\felic\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\io_scene_halo\global_functions\global_functions.py", line 1415, in run_code
    toolset_exec(f"""locals()['__this_is_a_horrible_hack'] = {code_string}""")
  File "C:\Users\felic\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\io_scene_halo\global_functions\global_functions.py", line 1405, in toolset_exec
    exec(code, globals(), caller_locals)
  File "<string>", line 1, in <module>
  File "C:\Users\felic\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\io_scene_halo\file_ass\import_ass.py", line 32, in load_file
    build_scene(context, filepath, report)
  File "C:\Users\felic\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\io_scene_halo\file_ass\build_scene.py", line 327, in build_scene
    vertex_weights_sets, regions = mesh_processing.generate_mesh_retail(context, ASS, ass_object.vertices, ass_object.triangles, object_data, "halo3", random_color_gen)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felic\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\io_scene_halo\global_functions\mesh_processing.py", line 742, in generate_mesh_retail
    if not global_functions.string_empty_check(mat.asset_name):
                                               ^^^^^^^^^^^^^^
AttributeError: 'Material' object has no attribute 'asset_name'. Did you mean: 'asset_data'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\felic\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\io_scene_halo\global_functions\global_functions.py", line 1426, in run_code
    crash_report.report_crash()
  File "C:\Users\felic\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\io_scene_halo\crash_report.py", line 77, in report_crash
    dump_path = report.dump()
                ^^^^^^^^^^^^^
  File "C:\Users\felic\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\io_scene_halo\crash_report.py", line 58, in dump
    with open(file_name, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\felic\\blender_halo_crashes\\1732770737_crash.zip'

![Capture](https://github.com/user-attachments/assets/56c19219-9980-4a7b-b04f-58859dc9e19e)

**Comment by General-101** [comment]
https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/releases/tag/304

Check out latest and see if you see that now

**Comment by GodHatesWeebs** [comment]
Yeah man works fine now, thank you a lot 
if anything comes of it ill be sure to show you
