### ISSUE TITLE
ValueError: register_class(...): already registered as a subclass 'Halo_SurfaceFlags'

### ISSUE THREAD

**Issue by Nukedrabbit95** [General-101/Halo-Asset-Blender-Development-Toolset#80]
```
Traceback (most recent call last):
  File "X:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\dsnv1\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_halo\__init__.py", line 65, in register
    module.register()
  File "C:\Users\dsnv1\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_halo\global_ui\__init__.py", line 210, in register
    bpy.utils.register_class(clshalo)
ValueError: register_class(...): already registered as a subclass 'Halo_SurfaceFlags'
```

I get this error enabling the addon, which causes it to fail to load. Tried on Blender 3.5 and 4.0, with multiple versions of the addon going all the way back to 162. Same result every time.

**Comment by Nukedrabbit95** [comment]
Update: it works after restarting Blender and re-enabling the addon, however it disables itself again every time Blender is launched. And if you disable it yourself, the issue comes back, and it can't be re-enabled until you restart Blender.

**Comment by General-101** [comment]
This should be solved on latest.
