### ISSUE TITLE
Cannot import tags. ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by HaloDump** [General-101/Halo-Asset-Blender-Development-Toolset#81]
I cannot import tags (.gbxmodel etc.). I just get an error telling me the PIL module is not installed. Tried with previous versions of Blender and the addons with no luck either. Not sure if this is a bug or if there is an unlisted requirement for the addon that was not made apparent.

Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_halo\file_tag\import_tag.py", line 32, in <module>
    from .build_scene import build_mesh as build_scene_model
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_halo\file_tag\build_scene\build_mesh.py", line 31, in <module>
    from ..h1.file_model.build_mesh import get_geometry_layout as get_retail_h1_geometry_layout
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_halo\file_tag\h1\file_model\build_mesh.py", line 33, in <module>
    from ....global_functions import shader_processing, mesh_processing, global_functions
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_halo\global_functions\shader_processing.py", line 33, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by HaloDump** [comment]
Fix for anyone who encounters this problem: 
Open Powershell in your Blender install's python folder.

> Install Location\Blender\4.0\python\bin

In Powershell, type: 
> .\python -m pip install Pillow

Hit enter. This will install the missing module and allow you to import tags. Hope this helps anyone with this issue.
