### ISSUE TITLE
Can't import sbsp from HCEEK

### ISSUE THREAD

**Issue by AlexisJonsson** [General-101/Halo-Asset-Blender-Development-Toolset#83]
When importing structure bsp from the HCEEK into Blender, the add-on errors out and doesn't import any geo.

I'm on Blender 4.0 and the add-on version is release 205.

```
Traceback (most recent call last):
  File "C:\Users\Alexis\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_halo\global_functions\global_functions.py", line 1339, in run_code
    toolset_exec(f"""locals()['__this_is_a_horrible_hack'] = {code_string}""")
  File "C:\Users\Alexis\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_halo\global_functions\global_functions.py", line 1329, in toolset_exec
    exec(code, globals(), caller_locals)
  File "<string>", line 1, in <module>
  File "C:\Users\Alexis\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_halo\file_tag\import_tag.py", line 190, in load_file
    build_scene.build_scene(context, ASSET, "retail", game_title, 0, fix_rotations, empty_markers, report)
  File "C:\Users\Alexis\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_halo\file_tag\build_scene\build_bsp.py", line 56, in build_scene
    bpy.ops.object.mode_set(mode='EDIT')
  File "C:\Program Files\Blender\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object
Dumped crash report to C:\Users\Alexis\blender_halo_crashes\1705751923_crash.zip
```

[1705751923_crash.zip](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/files/13997786/1705751923_crash.zip)

**Comment by General-101** [comment]
Can't repo so assumed either fixed or incredibly specific. Reopen if this happens again plz.
